### ISSUE TITLE
Please extend your DataFrames [compat] to "^0.21"

### ISSUE THREAD

**Issue by drcxcruz** [nredell/ShapML.jl#4]
Hello,

We are not able to update packages because ShapML is using an old version of DataFrame.

Here the problem is ShapML which has not lifted their DataFrames [compat]:

https://github.com/nredell/ShapML.jl/blob/56f37f672704d0016cf97fe665a6856ff895dffc/Project.toml#L15

Please, ShapML.jl team, extend your DataFrames [compat] to "^0.21"

thank you

**Comment by nredell** [comment]
Yes. I should be able to do this within the next day or so. I did read your other open issue and I'm not sure when I'll be able to get to that. Life has recently interrupted my open source time. But this fix is easy enough.

**Comment by drcxcruz** [comment]
hi,

I understand.  Life is first!

Thanks for fixing the data frame issue soon.  We appreciate it!!

For now, I was able to work around the out of memory issue.  I selected a smaller number of random rows instead of using the entire file.  but that trick only worked in the sequential version.  The parallel version is still running our of memory unless the number of rows is small.

Let me ask you a question.  You use sample_size = 60.  Why 60?  I am using sample_size = 33 in the hopes of reducing the memory usage.   is a higher sample size better? 

ShapML.shap( explain=explain,
                                reference=reference,
                                model=mtm,
                                predict_function=predictor,
                                sample_size=sample_size,
                                seed=1
            )

thank you

**Comment by nredell** [comment]
The package dependency is updated, but I haven't tested it. After testing, I could push a patch to the official Julia registry here shortly. I'm mostly off the grid for the foreseeable future so a quick patch is about all I can do.

I never got around to writing it up, but when I was profiling multi-thread vs. multi-core I noticed a clear trade off between peak memory consumption and speed: Each approach was good at one but not the other. I forget which was which. But the one thing that I wanted to do was add multi-thread support over feature sampling AND Monte Carlo samples because this algorithm runs in two completely parallelizable loops...but I never added this because I didn't do the testing to see if it was thread safe and would give reproducible results. I have a hunch that multi-threading both loops would be the fastest option for most problems.

I went through a fair bit of effort to reduce memory consumption and improve speed by exploiting the structure of the data/algorithm/problem with fancy indexing schemes and relying on `DataFrames` as little as possible. The `shap()` function is about as lean as I know how to make it.

I use 60 because  it's easy to invoke the central limit theorem and not have to worry about the problem. If Shapley values follow, say, an extreme value distribution for a certain class of problem then 6000 probably makes more sense (also focusing on a few target features of interest really helps instead of getting Shapley values for all features). But 60 is really based off of practical experience on small ML problems. Also, the number of samples should scale with the number of features: more features -> more samples to get adequate coverage. The `shap` Python package sets an adaptive default based on the number of features in the data. I could see a simulation showing the tradeoff between features, Monte Carlo sample size, runtime, and parameter recovery etc. making for a cool blog post.

**Comment by drcxcruz** [comment]
hi

Thank you for your time, expertise, and teaching.  It is very interesting stuff. 

I am going to implement your suggestion of "..focusing on a few target features of interest really helps instead of getting Shapley values for all features.."  I am thinking of
1. Run a couple of classical feature reduction models like forward/backward feature selection and elastic net
2. Unite their feature results  
3. Run ShapML with the union of the results which should be a subset of the original columns

"I could see a simulation showing the trade-off between features, Monte Carlo sample size, runtime, and parameter recovery etc. making for a cool blog post."  is a great idea.   Let me see if I get some time to do this for you.  I would might need you guidance, however :)

Cheers,

**Comment by drcxcruz** [comment]
hi

https://github.com/nredell/ShapML.jl  says

> **Releases**
> No releases published

how do we update to the latest version?  thanks

> (@v1.4) pkg> update ShapML
>    Updating registry at `C:\Users\BCP\.julia\registries\General`
>    Updating git-repo `https://github.com/JuliaRegistries/General.git`
>    Updating `C:\Users\BCP\.julia\environments\v1.4\Project.toml`
>  [no changes]
>    Updating `C:\Users\BCP\.julia\environments\v1.4\Manifest.toml`
>  [no changes]
> 
> (@v1.4) pkg>                                   
>

**Comment by nredell** [comment]
`Pkg.add(PackageSpec(url = "https://github.com/nredell/ShapML.jl"))`

This will let you update from the GitHub repo. I still need to test before pushing to the Julia registry. I'm mostly on mobile right now so I can't be as responsive as I'd like to be as far as coding goes. I will push a patch to the Julia registry in a day or so.
